# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [3]:
import pandas as pd

df1 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
df2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")
df3 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")

In [4]:
df1.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [5]:
df2.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.2,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.6,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.2,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.2,Corporate Auto,Two-Door Car

In [6]:
df3.head()

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

In [7]:
df1.columns = df1.columns.str.lower()
df2.columns = df2.columns.str.lower()
df3.columns = df3.columns.str.lower()

In [8]:
df1.columns = df1.columns.str.lower().str.replace(" ", "_")
df2.columns = df2.columns.str.lower().str.replace(" ", "_")
df3.columns = df3.columns.str.lower().str.replace(" ", "_")

df1 = df1.rename(columns={"st": "state"})
df2 = df2.rename(columns={"st": "state"})

In [9]:
df1["number_of_open_complaints"] = df1["number_of_open_complaints"].astype(str).str.split("/").str[1]

df1["number_of_open_complaints"] = pd.to_numeric(df1["number_of_open_complaints"], errors="coerce")

df1

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df2["number_of_open_complaints"] = df2["number_of_open_complaints"].astype(str).str.split("/").str[1]

df2["number_of_open_complaints"] = pd.to_numeric(df2["number_of_open_complaints"], errors="coerce")

df2

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,total_claim_amount,policy_type,vehicle_class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,0,633.600000,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,0,547.200000,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,0,537.600000,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1,1027.200000,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,0,451.200000,Corporate Auto,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...
991,HV85198,Arizona,M,Master,847141.75%,63513,70,0,185.667213,Personal Auto,Four-Door Car
992,BS91566,Arizona,F,College,543121.91%,58161,68,0,140.747286,Corporate Auto,Four-Door Car
993,IL40123,Nevada,F,College,568964.41%,83640,70,0,471.050488,Corporate Auto,Two-Door Car
994,MY32149,California,F,Master,368672.38%,0,96,0,28.460568,Personal Auto,Two-Door Car
995,SA91515,California,M,Bachelor,399258.39%,0,111,0,700.349052,Personal Auto,SUV

In [11]:
df1_columns = df1.columns
df_merged = pd.concat([df1[df1_columns], df2[df1_columns], df3[df1_columns]], ignore_index=True)

df_merged

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
12069,LA72316,California,M,Bachelor,23405.98798,71941.0,73.0,0.0,Personal Auto,Four-Door Car,198.234764
12070,PK87824,California,F,College,3096.511217,21604.0,79.0,0.0,Corporate Auto,Four-Door Car,379.200000
12071,TD14365,California,M,Bachelor,8163.890428,0.0,85.0,3.0,Corporate Auto,Four-Door Car,790.784983
12072,UP19263,California,M,College,7524.442436,21941.0,96.0,0.0,Personal Auto,Four-Door Car,691.200000
12073,Y167826,California,M,College,2611.836866,0.0,77.0,0.0,Corporate Auto,Two-Door Car,369.600000

In [12]:
df_merged["gender"] = df_merged["gender"].str.lower().str.strip().replace({
    "m": "M",
    "male": "M",
    "f": "F",
    "female": "F",
    "femal": "F"
})

print(df_merged["gender"].unique())

[nan 'F' 'M']

In [13]:
df_merged["state"] = df_merged["state"].str.lower().str.strip().replace({
    "cali": "california",
    "AZ": "arizona",
    "az": "arizona",
    "wa": "washington",
})

print(df_merged["state"].unique())

['washington' 'arizona' 'nevada' 'california' 'oregon' nan]

In [14]:
df_merged["education"] = df_merged["education"].str.lower().str.strip().replace({
    "bachelor": "bachelors"
})

print(df_merged["education"].unique())

['master' 'bachelors' 'high school or below' 'college' 'doctor' nan]

In [15]:
df_merged["customer_lifetime_value"] = df_merged["customer_lifetime_value"].astype(str).str.strip().str.replace("%", "")

print(df_merged["customer_lifetime_value"].unique())

['nan' '697953.59' '1288743.17' ... '8163.890428' '7524.442436'
 '2611.836866']

In [16]:
df_merged["vehicle_class"] = df_merged["vehicle_class"].replace(
    {"Sports Car": "Luxury", "Luxury SUV": "Luxury", "Luxury Car": "Luxury"}
)

print(df_merged["vehicle_class"].unique())

['Four-Door Car' 'Two-Door Car' 'SUV' 'Luxury' nan]

In [17]:
df_merged["customer_lifetime_value"] = pd.to_numeric(df_merged["customer_lifetime_value"], errors="coerce")

df_merged.dtypes

customer                      object
state                         object
gender                        object
education                     object
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints    float64
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object

In [18]:
df_cleaned = df_merged.dropna(how="all")

df_cleaned.isnull()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,False,False,True,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
12069,False,False,False,False,False,False,False,False,False,False,False
12070,False,False,False,False,False,False,False,False,False,False,False
12071,False,False,False,False,False,False,False,False,False,False,False
12072,False,False,False,False,False,False,False,False,False,False,False
12073,False,False,False,False,False,False,False,False,False,False,False

In [19]:
df_cleaned["gender"] = df_cleaned["gender"].fillna("U")


print(df_cleaned["gender"].unique())

['U' 'F' 'M']

/var/folders/s4/7wsslyw16w9bqtllmwg3nfbm0000gp/T/ipykernel_93013/2964117270.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["gender"] = df_cleaned["gender"].fillna("U")

In [20]:
median_clv = df_cleaned["customer_lifetime_value"].median()


df_cleaned["customer_lifetime_value"].fillna(median_clv, inplace=True)

/var/folders/s4/7wsslyw16w9bqtllmwg3nfbm0000gp/T/ipykernel_93013/2670235517.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_cleaned["customer_lifetime_value"].fillna(median_clv, inplace=True)
/var/folders/s4/7wsslyw16w9bqtllmwg3nfbm0000gp/T/ipykernel_93013/2670235517.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["customer_lifetime_value"].fillna(median_clv, inplace=True)

In [21]:
df_cleaned[df_cleaned.isna().any(axis=1)]

Empty DataFrame
Columns: [customer, state, gender, education, customer_lifetime_value, income, monthly_premium_auto, number_of_open_complaints, policy_type, vehicle_class, total_claim_amount]
Index: []

In [22]:
df_cleaned["number_of_open_complaints"] = df_cleaned["number_of_open_complaints"].fillna("0")


print(df_cleaned["number_of_open_complaints"].unique())

[0. 2. 1. 3. 5. 4.]

/var/folders/s4/7wsslyw16w9bqtllmwg3nfbm0000gp/T/ipykernel_93013/2437486067.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cleaned["number_of_open_complaints"] = df_cleaned["number_of_open_complaints"].fillna("0")

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [53]:
df_customer = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")

In [57]:
df_customer.columns

Index(['unnamed:_0', 'customer', 'state', 'customer_lifetime_value',
       'response', 'coverage', 'education', 'effective_to_date',
       'employmentstatus', 'gender', 'income', 'location_code',
       'marital_status', 'monthly_premium_auto', 'months_since_last_claim',
       'months_since_policy_inception', 'number_of_open_complaints',
       'number_of_policies', 'policy_type', 'policy', 'renew_offer_type',
       'sales_channel', 'total_claim_amount', 'vehicle_class', 'vehicle_size',
       'vehicle_type', 'month'],
      dtype='object')

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [61]:

pivot_table = df_customer.pivot_table(
    values="monthly_premium_auto", 
    index="sales_channel", 
    aggfunc="sum"  # Summing total revenue per sales channel
)

pivot_table = pivot_table.rename(columns={"monthly_premium_auto": "total_revenue"})

display(pivot_table)

               total_revenue
sales_channel
Agent                 386335
Branch                280953
Call Center           197970
Web                   151511

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [69]:
pivot_table2 = df_customer.pivot_table(
    values="customer_lifetime_value", 
    index="gender", 
    columns="education", 
    aggfunc="mean" 
)

display(pivot_table2)
print("Analysis: We can see that females with high school education or below have the highest mean clv. This company should consider targeting their sales efforts towards this demo.")

education,Bachelor,College,Doctor,High School or Below,Master
gender,,,,,
F,7874.269478,7748.823325,7328.508916,8675.220201,8157.053154
M,7703.601675,8052.459288,7415.333638,8149.687783,8168.832659

Analysis: We can see that females with high school education or below have the highest mean clv. This company should consider targeting their sales efforts towards this demo.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [30]:
# Your code goes here